---
title: "Linear regression of corals and inverts"
author: "Journ Galvan"
date: "4/23/2020"
output: html_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
```

### Code referenced from lines 83-125 in "Coral Condition Data Preliminary Analysis - Stier Lab Moorea Summer 2019" Author: Joseph Curtis
```{r load libraries}
# Load libraries
library(here)
library(tidyverse)
library(vegan)
library(reshape)
library(ggplot2)
```

```{r load data}
# Load data
branch_width <- read.csv(here("photogrammetry_data/branchwidth_data.csv"))
coral_pg <- read.csv(here("photogrammetry_data/galvan_journ_datasheet_v2.csv"))
coral_field <- read.csv(here("photogrammetry_data/field_experiment_colony_measurements_moorea_summer2019.csv"))
cafi_surveys <- read.csv(here("cafi_data/revised_cafi_data_moorea_summer2019_11_27.csv"))
cafi_field <- read.csv(here("cafi_data/prelim_cafi_counts_moorea_summer2019.csv"))
```


### Incorporate CAFI data
```{r}
# Uncount CAFI data from field experiment
cafi_field_long <- uncount(cafi_field, count) %>% select(order, coral_id, type, code, cafi_size_mm, known_unknown) %>%
  separate(coral_id, c("reef", NA), remove = FALSE)

cafi_surveys <- cafi_surveys %>% select(sort, coral_id, type, code, cafi_size_mm, known_unknown) %>%
  separate(coral_id, c("reef", NA), remove = FALSE)
```

```{r}
# Analyze known organisms until further data cleaning
cafi_combined <- bind_rows(cafi_surveys, cafi_field_long) %>% 
  filter(known_unknown == "known")
```

```{r}
# Calculate CAFI richness, abundance, and diversity (shannon weiner) for each coral
cafi_summarized <- group_by(cafi_combined, coral_id) %>%
  summarise(num_cafi = n(), cafi_richness = length(unique(code)), cafi_present = paste(sort(unique(code)), collapse = ";"))

cafi_summarized$sw <- cafi_combined %>% 
  count(code, coral_id = coral_id) %>% 
  spread(code,n) %>% 
  mutate_all(list(~replace_na(.,0))) %>% 
  select(-coral_id) %>% 
  diversity(index = "shannon")
```


### Incorporate coral data 
```{r}
# Clean field data
coral_field2 <- coral_field %>%
  dplyr::rename(branch = branch_width)

# Clean photogrammetry morphometric data
coral_pg$volume_pg <- as.numeric(as.character(coral_pg$volume_pg)) # Convert factor to numeric

# Clean photogrammetry branch width data and take averages of branch distance for each coral
branch_width$branch_distance_mm <- as.numeric(as.character(branch_width$branch_distance_mm)) # Convert factor to numberic

branch_w_summarized <- group_by(branch_width, coral_id) %>% 
  summarise(avg_w_mm = sum(branch_distance_mm)/n(), 
            measurements = length(unique(replicate_measurement)), 
            locations = paste(sort(unique(location)), collapse = ";"))
```

```{r}
# Add branch, cafi, and size_class columns from field data to morphometric photogrammetry data 
coral_dim <- merge(coral_pg, branch_w_summarized, by = "coral_id") %>%
  merge(coral_field2, by = "coral_id") %>%
  select(coral_id, row, column, branch, cafi, size_class, volume_pg, surface_area, interstitial_volume, avg_w_mm) 
# could also use lapply(cafi_coral)
```


### Combine cleaned CAFI data with photogrammetry coral data
```{r}
# Combine cafi_summarized with coral_dim
cafi_coral <- merge(cafi_summarized, coral_dim, by ="coral_id")
```


### Visualize invertebrate data
```{r}
# Scatter plot of wide volume and invert abundance
cafi_coralwide <- cafi_coral %>% filter(branch == "wide")
plot(num_cafi~volume_pg, data = cafi_coralwide,
    xlab = "Coral volume m^(3)", xlim = c(0,0.0156),
    ylab = "CAFI abundance", ylim = c(0,50), 
    main = "Wide coral volume and invert abundance")
# Overlay best fit line on existing plot
fit <- lm(num_cafi~volume_pg, data = cafi_coralwide)
abline(fit,col = "green")

# Scatter plot of tight volume and invert abundance
cafi_coraltight <- cafi_coral %>% filter(branch == "tight")
plot(num_cafi~volume_pg, data = cafi_coraltight,
    xlab = "Coral volume m^(3)", xlim = c(0,0.0156),
    ylab = "CAFI abundance", ylim = c(0,50), 
    main = "Tight coral volume and invert abundance")
# Overlay best fit line on existing plot
fit <- lm(num_cafi~volume_pg, data = cafi_coraltight)
abline(fit,col = "green")

# Scatter plot of volume and invert abundance
plot(num_cafi~volume_pg, data = cafi_coral,
    xlab = "Coral volume m^(3)", ylab = "CAFI abundance", main = "Coral volume and invert abundance")
# Overlay best fit line on existing plot
fit <- lm(num_cafi~volume_pg, data = cafi_coral)
abline(fit,col = "green")

# ggplot
#cafi_coralscatter <- ggplot(cafi_coral, aes(x=volume_pg, y=num_cafi)) +
  #geom_point() +
  #geom_smooth(method=lm, color="red", fill="#69b3a2", se=FALSE) +
  #theme_ipsum()

#cafi_coralscatter

```

```{r}
# Scatter plot of average branch width and and invert abundance
cafi_coralwide <- cafi_coral %>% filter(branch == "wide")
plot(num_cafi~avg_w_mm, data = cafi_coralwide,
    xlab = "average branch width (m)", xlim = c(0,1 + max(cafi_coral$avg_w_mm, na.rm = TRUE)),
    ylab = "CAFI abundance", ylim = c(0, 1 + max(cafi_coral$num_cafi)), 
    main = "Wide avg. branch distance and invert abundance")
# Overlay best fit line on existing plot
fit <- lm(num_cafi~avg_w_mm, data = cafi_coralwide)
abline(fit,col = "green")

# Scatter plot of average branch tight and invert abundance
cafi_coraltight <- cafi_coral %>% filter(branch == "tight")
plot(num_cafi~avg_w_mm, data = cafi_coraltight,
    xlab = "average branch width (m)", xlim = c(0, 1 + max(cafi_coral$avg_w_mm, na.rm = TRUE)),
    ylab = "CAFI abundance", ylim = c(0, 1 + max(cafi_coral$num_cafi)), 
    main = "Tight avg. branch distance and invert abundance")
# Overlay best fit line on existing plot
fit <- lm(num_cafi~avg_w_mm, data = cafi_coraltight)
abline(fit,col = "green")
```

```{r}
# Bargraph of invert abundance
ggplot(cafi_coral, aes(y=num_cafi, x=branch)) +
  geom_bar(position = "dodge", stat = "identity")

```


### Dataframe of trapezid abundance and combine with photogrammetry coral data
```{r}
# Calculate Trapezid abundance and richness for each coral
its_a_trap <- cafi_combined %>% filter(str_detect(code, "^TR"))
trap_summarized <- group_by(its_a_trap, coral_id) %>%
  summarise(num_cafi = n(), cafi_richness = length(unique(code)), cafi_present = paste(sort(unique(code)), collapse = ";"))
```

```{r}
# Combine with photogrammetry data
trap_w_coral_dim <- merge(trap_summarized, coral_dim, by = "coral_id")

trap_w_coral_dim$num_trap <- trap_w_coral_dim$num_cafi %>% replace_na(0) %>% rename("num_trap")
trap_w_coral_dim$trap_richness <- trap_w_coral_dim$cafi_richness %>% replace_na(0) %>% rename("trap_richness")
trap_w_coral_dim <- trap_w_coral_dim %>% select(-cafi_richness, -num_cafi)
```


### Visualize Trapezid data
```{r}
# Scatter plot of volume and trapezid abundance
plot(num_trap~volume_pg, data = trap_w_coral_dim,
     xlab = "Coral volume m^3",
     ylab = "Trapezid crab abundance", main = "Coral volume and trapezid crab abundance")
# Overlay best fit line on existing plot
fit <- lm(num_trap~volume_pg, data = trap_w_coral_dim)
abline(fit,col = "green")

# Scatter plot of wide volume and trapezid abundance
trap_w_coral_dimwide <- trap_w_coral_dim %>% filter(branch == "wide")
plot(num_trap~volume_pg, data = trap_w_coral_dimwide,
     xlab = "Coral volume m^3",
     ylab = "Trapezid crab abundance", main = "Wide coral volume and trapezid crab abundance")
# Overlay best fit line on existing plot
fit <- lm(num_trap~volume_pg, data = trap_w_coral_dimwide)
abline(fit,col = "green")

# Scatter plot of tight volume and trapezid abundance
trap_w_coral_dimtight <- trap_w_coral_dim %>% filter(branch == "tight")
plot(num_trap~volume_pg, data = trap_w_coral_dimtight,
     xlab = "Coral volume m^3",
     ylab = "Trapezid crab abundance", main = "Tight coral volume and trapezid crab abundance")
# Overlay best fit line on existing plot
fit <- lm(num_trap~volume_pg, data = trap_w_coral_dimtight)
abline(fit,col = "green")
```


